version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todos-list-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gv25qf59h5i9"
s3_prefix = "todos-list-serverless"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
