AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-serverless

  SAM Template for todo-list-serverless

Globals:
  Function:
    Timeout: 3

Resources:
  DynamoDBDatabase:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "item_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "item_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: Todos

  WebsiteCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: website_checker/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        WebsiteChecker:
          Type: Api
          Properties:
            Path: /checker
            Method: get
  CreateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create_todo/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebsiteCheckerApi:
    Description: "API Gateway endpoint URL for Prod stage for Website Checker function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/checker/"
  WebsiteCheckerFunction:
    Description: "Website Checker Function ARN"
    Value: !GetAtt WebsiteCheckerFunction.Arn